"""AI Assistant page powered by Gemini 1.5 Flash."""

import streamlit as st
from utils.gemini_helper import ask_gemini, generate_alert_summary
from utils.data_generator import get_bed_data, get_icu_data, get_equipment_data


_SUGGESTED_QUESTIONS = [
    "Which departments need immediate resource reallocation?",
    "What actions should I take if ICU occupancy exceeds 90%?",
    "Summarise the critical equipment risks across all branches.",
    "How can I optimize bed turnover to improve availability?",
    "Which branch is most at risk for resource shortage today?",
    "Draft a patient surge contingency plan for the current situation.",
    "What staffing adjustments do you recommend given current occupancy?",
    "Explain the impact of the offline equipment on patient care.",
]


def _build_context(branch: str) -> str:
    """Compile a concise data snapshot for injection into the Gemini prompt."""
    bed_df   = get_bed_data(branch)
    icu_df   = get_icu_data(branch)
    equip_df = get_equipment_data(branch)

    # Top 5 most occupied departments
    top_beds = (
        bed_df.sort_values("Occupancy (%)", ascending=False)
        .head(5)[["Branch", "Department", "Occupancy (%)", "Available"]]
        .to_string(index=False)
    )

    # ICU summary
    icu_summary = icu_df[["Branch", "ICU Occupied", "ICU Available", "Occupancy (%)"]].to_string(index=False)

    # Equipment issues
    issues = equip_df[equip_df["Status"].isin(["Offline", "Under Maintenance"])]
    equip_issues = (
        issues[["Branch", "Equipment", "Unit #", "Status", "Department"]].to_string(index=False)
        if not issues.empty else "None — all units operational or in use."
    )

    return (
        f"=== TOP 5 MOST OCCUPIED DEPARTMENTS ===\n{top_beds}\n\n"
        f"=== ICU STATUS BY BRANCH ===\n{icu_summary}\n\n"
        f"=== EQUIPMENT ISSUES ===\n{equip_issues}\n"
    )


def render(branch: str, kpi: dict):
    st.subheader("🤖 AI-Powered Hospital Operations Assistant")
    st.caption(
        "Powered by **Google Gemini 1.5 Flash** · Ask anything about current resource status, "
        "patient flow, contingency planning, or operational recommendations."
    )

    # ── API key guard ─────────────────────────────────────────────────────────
    import os
    api_key = os.getenv("GEMINI_API_KEY", "")
    if not api_key:
        st.warning(
            "⚠️ **Gemini API key not set.**\n\n"
            "Enter your key in the sidebar to activate AI features. "
            "Get a free key at [aistudio.google.com](https://aistudio.google.com)."
        )

    # ── Auto AI Alert Summary ─────────────────────────────────────────────────
    st.markdown("### 📢 Operational Alert Summary")
    st.caption("Auto-generated by Gemini based on the current hospital snapshot.")

    if st.button("🔄 Generate / Refresh AI Alert", use_container_width=True):
        with st.spinner("Gemini is analysing the current hospital state…"):
            summary = generate_alert_summary(kpi)
        st.session_state["ai_alert"] = summary

    if "ai_alert" in st.session_state:
        st.markdown(
            f'<div class="ai-alert">{st.session_state["ai_alert"]}</div>',
            unsafe_allow_html=True,
        )

    st.markdown("---")

    # ── Chat Interface ────────────────────────────────────────────────────────
    st.markdown("### 💬 Interactive Chat")

    # Initialise chat history
    if "chat_history" not in st.session_state:
        st.session_state["chat_history"] = []

    # Suggested questions as quick-fire chips
    st.markdown("**💡 Suggested Questions**")
    chip_cols = st.columns(4)
    for i, q in enumerate(_SUGGESTED_QUESTIONS):
        with chip_cols[i % 4]:
            if st.button(q, key=f"chip_{i}", use_container_width=True):
                st.session_state["pending_question"] = q

    st.markdown("---")

    # Render chat history
    for msg in st.session_state["chat_history"]:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    # Handle pending question from chip
    pending = st.session_state.pop("pending_question", None)

    # Chat input
    user_input = st.chat_input(
        "Ask about bed occupancy, ICU, equipment, contingency plans…",
    )
    question = pending or user_input

    if question:
        # Display user message
        with st.chat_message("user"):
            st.markdown(question)
        st.session_state["chat_history"].append({"role": "user", "content": question})

        # Get Gemini response
        with st.chat_message("assistant"):
            with st.spinner("Gemini is thinking…"):
                context = _build_context(branch)
                response = ask_gemini(question, context)
            st.markdown(response)
        st.session_state["chat_history"].append({"role": "assistant", "content": response})

    # ── Clear chat ────────────────────────────────────────────────────────────
    if st.session_state.get("chat_history"):
        if st.button("🗑️ Clear Chat History", use_container_width=False):
            st.session_state["chat_history"] = []
            st.rerun()

    st.markdown("---")

    # ── Live context snapshot ─────────────────────────────────────────────────
    with st.expander("🔍 View Current Hospital Context Sent to Gemini", expanded=False):
        st.code(_build_context(branch), language="text")
